valor1 = input('Digite o primeiro número inteiro: ')
valor2 = input('Digite o segundo número inteiro: ')
print('O número', valor1, 'é igual ao número', valor2, '?', valor1 == valor2)
print('O número', valor1, 'é maior que o número', valor2, '?', valor1 > valor2)
print('O número', valor1, 'é menor que o número', valor2, '?', valor1 < valor2)
print('O número', valor1, 'é maior ou igual ao número', valor2, '?', valor1 >= valor2)
print('O número', valor1, 'é menor ou igual ao número', valor2, '?', valor1 <= valor2)